/*
  CATÁLOGO DE ITENS E PONTOS DE TROCA
  ------------------------------------------------------------
  "pontos" NÃO é preço em reais. É um valor relativo que usamos
  só para permitir trocas equivalentes no simulador (ex: 1 item
  de 4 pontos pode ser trocado por 2 itens de 2 pontos cada).

  ESTES VALORES SÃO UM PONTO DE PARTIDA ESTIMADO — a Cesta Básica
  Aliança deve revisar e ajustar cada "pontos" para refletir o
  valor de troca real de cada produto antes de usar com clientes.
  Basta editar os números abaixo, nada mais no site precisa mudar.
*/

const CATALOGO_ITENS = [
  { id: "arroz5kg",        nome: "Pacote de 5kg de Arroz",              categoria: "Mercearia", pontos: 5 },
  { id: "acucar5kg",       nome: "Pacote de 5kg de Açúcar",              categoria: "Mercearia", pontos: 4 },
  { id: "feijao",          nome: "Pacote de Feijão",                    categoria: "Mercearia", pontos: 3 },
  { id: "oleo1l",          nome: "Óleo (1L)",                            categoria: "Mercearia", pontos: 1 },
  { id: "cafe",            nome: "Pacote de Café Mineiro",               categoria: "Mercearia", pontos: 3 },
  { id: "farinhatrigo",    nome: "Farinha de Trigo (1kg)",               categoria: "Mercearia", pontos: 2 },
  { id: "macarrao",        nome: "Pacote de Macarrão",                   categoria: "Mercearia", pontos: 1 },
  { id: "alho",            nome: "Cabeça de Alho",                      categoria: "Mercearia", pontos: 1 },
  { id: "refrigerante2l",  nome: "Refrigerante (2L)",                    categoria: "Bebidas",   pontos: 2 },
  { id: "bolachareco",     nome: "Bolacha Recheada Itamaraty",           categoria: "Mercearia", pontos: 2 },
  { id: "bolacharosq",     nome: "Bolacha Rosquinha",                    categoria: "Mercearia", pontos: 1 },
  { id: "sucoempo",        nome: "Pacote de Suco em Pó",                 categoria: "Bebidas",   pontos: 1 },
  { id: "sardinha",        nome: "Lata de Sardinha",                    categoria: "Mercearia", pontos: 2 },
  { id: "maionese",        nome: "Sachê de Maionese",                   categoria: "Mercearia", pontos: 1 },
  { id: "miojo",           nome: "Macarrão Instantâneo (Miojo)",        categoria: "Mercearia", pontos: 1 },
  { id: "molhotomate",     nome: "Sachê de Molho de Tomate",            categoria: "Mercearia", pontos: 1 },
  { id: "farofa",          nome: "Pacote de Farofa Temperada",           categoria: "Mercearia", pontos: 1 },
  { id: "vinagre",         nome: "Vinagre (1L)",                        categoria: "Mercearia", pontos: 1 },
  { id: "leitecondensado", nome: "Lata de Leite Condensado",            categoria: "Mercearia", pontos: 2 },
  { id: "cremeleite",      nome: "Lata de Creme de Leite",              categoria: "Mercearia", pontos: 2 },
  { id: "ovos",            nome: "Bandeja de Ovos",                     categoria: "Mercearia", pontos: 3 },
  { id: "coxasobrecoxa",   nome: "Pacote de Coxa e Sobrecoxa",           categoria: "Mercearia", pontos: 4 },
  { id: "margarina",       nome: "Pote de Margarina",                   categoria: "Mercearia", pontos: 2 },
  { id: "milho",           nome: "Lata de Milho",                       categoria: "Mercearia", pontos: 1 },
  { id: "nescau",          nome: "Achocolatado Nescau",                 categoria: "Mercearia", pontos: 3 },
  { id: "salsichao",       nome: "Salsichão Grande",                    categoria: "Mercearia", pontos: 3 },
  { id: "papelhigienico",  nome: "Pacote de Papel Higiênico (12 rolos)", categoria: "Limpeza",   pontos: 6 },
  { id: "detergente",      nome: "Detergente Ypê",                      categoria: "Limpeza",   pontos: 1 },
  { id: "amaciante",       nome: "Amaciante (2L)",                      categoria: "Limpeza",   pontos: 2 },
  { id: "aguasanitaria",   nome: "Água Sanitária (1L)",                  categoria: "Limpeza",   pontos: 1 },
  { id: "desinfetante",    nome: "Desinfetante",                        categoria: "Limpeza",   pontos: 2 },
  { id: "sabonete",        nome: "Sabonete",                            categoria: "Higiene",   pontos: 1 },
  { id: "laaco",           nome: "Pacote de Lã de Aço",                  categoria: "Limpeza",   pontos: 1 },
  { id: "esponja",         nome: "Esponja Multiuso",                    categoria: "Limpeza",   pontos: 1 },
  { id: "sabaobarra",      nome: "Pedra de Sabão em Barra",              categoria: "Limpeza",   pontos: 1 },
  { id: "omo",             nome: "Caixa de Sabão em Pó Omo",             categoria: "Limpeza",   pontos: 4 },
  { id: "pastadente",      nome: "Pasta de Dente",                      categoria: "Higiene",   pontos: 2 },
  { id: "limpadormultiuso",nome: "Limpador Multiuso",                   categoria: "Limpeza",   pontos: 2 },
];

// Composição da Cesta Padrão (mais de 50 itens)
const CESTA_PADRAO = [
  { id: "arroz5kg", quantidade: 3 },
  { id: "acucar5kg", quantidade: 1 },
  { id: "feijao", quantidade: 4 },
  { id: "oleo1l", quantidade: 4 },
  { id: "cafe", quantidade: 2 },
  { id: "farinhatrigo", quantidade: 1 },
  { id: "macarrao", quantidade: 2 },
  { id: "alho", quantidade: 2 },
  { id: "refrigerante2l", quantidade: 2 },
  { id: "bolachareco", quantidade: 1 },
  { id: "bolacharosq", quantidade: 1 },
  { id: "sucoempo", quantidade: 2 },
  { id: "sardinha", quantidade: 1 },
  { id: "maionese", quantidade: 1 },
  { id: "miojo", quantidade: 2 },
  { id: "molhotomate", quantidade: 2 },
  { id: "farofa", quantidade: 1 },
  { id: "vinagre", quantidade: 1 },
  { id: "leitecondensado", quantidade: 1 },
  { id: "cremeleite", quantidade: 1 },
  { id: "salsichao", quantidade: 1 },
  { id: "papelhigienico", quantidade: 1 },
  { id: "detergente", quantidade: 2 },
  { id: "amaciante", quantidade: 1 },
  { id: "aguasanitaria", quantidade: 1 },
  { id: "desinfetante", quantidade: 1 },
  { id: "sabonete", quantidade: 4 },
  { id: "laaco", quantidade: 1 },
  { id: "esponja", quantidade: 1 },
  { id: "sabaobarra", quantidade: 2 },
  { id: "omo", quantidade: 1 },
  { id: "pastadente", quantidade: 1 },
  { id: "limpadormultiuso", quantidade: 1 },
];

// Composição da Cesta Grande (mais de 60 itens)
const CESTA_GRANDE = [
  { id: "arroz5kg", quantidade: 4 },
  { id: "acucar5kg", quantidade: 2 },
  { id: "feijao", quantidade: 4 },
  { id: "oleo1l", quantidade: 4 },
  { id: "cafe", quantidade: 4 },
  { id: "farinhatrigo", quantidade: 1 },
  { id: "macarrao", quantidade: 2 },
  { id: "alho", quantidade: 2 },
  { id: "refrigerante2l", quantidade: 2 },
  { id: "nescau", quantidade: 1 },
  { id: "bolachareco", quantidade: 1 },
  { id: "bolacharosq", quantidade: 1 },
  { id: "sucoempo", quantidade: 4 },
  { id: "sardinha", quantidade: 1 },
  { id: "milho", quantidade: 1 },
  { id: "maionese", quantidade: 1 },
  { id: "miojo", quantidade: 2 },
  { id: "molhotomate", quantidade: 2 },
  { id: "farofa", quantidade: 1 },
  { id: "vinagre", quantidade: 1 },
  { id: "leitecondensado", quantidade: 1 },
  { id: "cremeleite", quantidade: 1 },
  { id: "ovos", quantidade: 1 },
  { id: "coxasobrecoxa", quantidade: 1 },
  { id: "salsichao", quantidade: 1 },
  { id: "margarina", quantidade: 1 },
  { id: "papelhigienico", quantidade: 1 },
  { id: "detergente", quantidade: 4 },
  { id: "amaciante", quantidade: 1 },
  { id: "aguasanitaria", quantidade: 1 },
  { id: "desinfetante", quantidade: 1 },
  { id: "sabonete", quantidade: 4 },
  { id: "laaco", quantidade: 1 },
  { id: "esponja", quantidade: 1 },
  { id: "sabaobarra", quantidade: 2 },
  { id: "omo", quantidade: 1 },
  { id: "pastadente", quantidade: 1 },
  { id: "limpadormultiuso", quantidade: 1 },
];
